version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11.4-browsers
    steps:
      - checkout
      - restore_cache:
          key: -v3-{{ checksum "yarn.lock" }}
      - run: 
          name: Install Dependencies
          command: |
            yarn
      - save_cache:
          key: -v3-{{ checksum "yarn.lock" }}
          paths:
            - "yarn.lock"
            - "node_modules"
      - run:
          name: Test
          command: |
            yarn test
      - run:
          name: Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t 56930aae-ed0b-4274-bb1b-53aa16152bcd
workflows:
  version: 2
  tests:
    jobs:
      - test