defaults: &defaults
  docker:
    - image: circleci/node:8.11.4-browsers
  working_directory: ~/repo

jobs:
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn test
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

whitelist: &whitelist
  paths:
    - .npmignore
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - README.md
    - coverage/*
    - dist/*
    - node_modules/*
    - package.json
    - src/*
    - test/*
    - tsconfig.json
    - tslint.json

workflows:
  build:
    jobs:
      - test
  version: 2

  